module: Komodio
title: Komodio
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/komodio/
build_tool_arguments:
 - -scheme
 - Komodio
# min_acl: internal
min_acl: private
output: Documentation
clean: true
theme: apple

exclude: /*/GeneratedAssetSymbols*

custom_categories:
  - name: General
    children:
    - KomodioApp
    - StaticSetting
    - Router
    - KodiCell
    - MediaItem
    - Parts
    - Hosts
    - Backport
  - name: Observable Classes
    children:
    - SceneState
    - AppDelegate
  - name: SwiftUI Views
    children:
    - MainView
    - SidebarView
    - ContentView
    - DetailView
    - CollectionView
    - StartView
    - ShelfView
    - MoviesView
    - MovieView
    - MovieSetView
    - TVShowsView
    - TVShowView
    - SeasonsView
    - SeasonView
    - EpisodeView
    - UpNextView
    - ArtistsView
    - ArtistView
    - MusicVideosView
    - MusicVideoView
    - MusicVideoAlbumView
    - PlaylistsView
    - StatisticsView
    - FavouritesView
    - HostItemView
    - SettingsView
    - KomodioPlayerView
    - SearchView
    - KodiSettingsView
    - PartsView
    - Buttons
    - Pickers
    - Modifiers
    - Styles
  - name: Extensions
    children:
    - ButtonStyle
    - LabelStyle
    - View
    - Color
